_target_: lightning.fabric.Fabric
accelerator: cuda
devices: ${..system.num_device}
num_nodes: ${..system.num_nodes}
strategy:
  _target_: lightning.fabric.strategies.DDPStrategy
  find_unused_parameters: false
precision: bf16-mixed
